config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
    devise_for :users, controllers: {
      sessions: 'users/sessions',
      passwords: 'users/passwords',
      registrations: 'users/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "homes#index"
  resources :homes
  resources :accounts
  resources :ewallets

  get '/home' => "homes#index"
  get '/ringgit' => "ewallets#ringgit"
  get '/rupiah' => "ewallets#rupiah"
  get '/sing' => "ewallets#sing"
  get '/baht' => "ewallets#baht"
  get '/remit' => "homes#remit"
  get '/transfer' => "homes#transfer"
  get '/value' => "homes#value"
  get '/crypto' => "homes#crypto"
  get '/currency' => "homes#currency"

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

	def index
		
		@ewallet = Ewallet.where(user_id: current_user.id).order(created_at: :desc)
		
		ringgit = @ewallet.where(currency: 'ringgitcoin')
		@ringgit = ringgit.sum(:balance)

		sing = @ewallet.where(currency: 'singcoin')
		@sing = sing.sum(:balance)

		rupiah = @ewallet.where(currency: 'rupiahcoin')
		@rupiah = rupiah.sum(:balance)

		baht = @ewallet.where(currency: 'bahtcoin')
		@baht = baht.sum(:balance)
	end

	def remit		
	end

	def crypto
	end

	def transfer
		@ewallet = Ewallet.new
		@account_a = Account.find_by_user_id(current_user.id)
		@user = Account.where(user_id: current_user.id)
		@users = User.all
		if params[:search]
    	@users = User.search(params[:search])
    	y = @users.first
    	@account_b = Account.find_by_user_id(y.id)
    	
    	if @user.sum(:amount)-100 > 0
    	ActiveRecord::Base.transaction do
    	@account_a.lock!
    	@account_b.lock!
		@account_a.amount -= 100
		@account_a.save!
		@account_b.amount += 100
		@account_b.save!
		end

		flash[:warning] = 'Your account not enough money to do the transfer!'
		redirect_to root_path
	end
	end
	end
	

	def value
		render 'homes/value'
	end

	def currency
		rm = Currency.find_by_code("MYR")
		idr = Currency.find_by_code("IDR")
		baht = Currency.find_by_code("THB")
		sgd = Currency.find_by_code("SGD")

		@rm_sg = rm.convert_to('SGD',100)
		@sg_rm = sgd.convert_to('MYR',1)
		@rm_idr = rm.convert_to('IDR',1)
		@idr_rm = idr.convert_to('MYR',1000)
		@rm_baht = rm.convert_to('THB',1)
		@baht_rm = baht.convert_to('MYR',1000)

	end
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/homes/_search.html.erb
<div class="input-group">
  <%= form_tag(transfer_path, :method => "get", id: "search-form") do %>
    <%= text_field_tag :search, params[:search],class: "phmargin", size: "23", placeholder: "email address"  %>
    <span class="input-group-btn">
      <%= submit_tag "Search", class: 'btn btn-default' %>
    </span>
  <% end %>
</div>

app/views/homes/crypto.html.erb
    <div class="jumbotron">
      <div class="container">
        <h1>Hello,Welcome to MeLAB Exchange!</h1>
        <p>The Safest, Fastest CryptoCurrency Exchange Platform in ASEAN. The best part is, we can directly credit any amount into your local bank account or use our reliable MeLAB ewallet to enjoy more benefit!</p>
        <p><a class="btn btn-primary btn-lg" href="https://coinmarketcap.com/" role="button">Latest Price &raquo;</a><center> <a class="btn btn-primary btn-lg" href="" role="button">Our Exchange Coming Soon ! </a></center></p>
      </div>
    </div>

    <div class="container">
      <!-- Example row of columns -->
      <div class="row">
        <div class="col-md-4">
          <h2>Recognition at universal level</h2>
          <p>Since cryptocurrency is not bound by the exchange rates, interest rates, transactions charges or other charges of any country; therefore it can be used at an international level without experiencing any problems.There is no other electronic cash system in which your account isn’t owned by someone else.
          Take PayPal, for example: if the company decides for some reason that your account has been misused, it has the power to freeze all of the assets held in the account, without consulting you. </p>
          <p><a class="btn btn-default" href="https://coinmarketcap.com/exchanges/volume/24-hour/" target="_blank" role="button">24hrs Exchange Volume &raquo;</a></p>
        </div>
        <div class="col-md-4">
          <h2>Decentralization</h2>
          <p>A global network of computers use blockchain technology to jointly manage the database that records Bitcoin transactions. That is, Bitcoin is managed by its network, and not any one central authority. Decentralization means the network operates on a user-to-user (or peer-to-peer) basis. The forms of mass collaboration this makes possible are just beginning to be investigated. </p>
          <p><a class="btn btn-default" href="https://www.coinbase.com/" target="_blank" role="button">World Top exchange &raquo;</a></p>
       </div>
        <div class="col-md-4">
          <h2>Fraud & Thief Proof</h2>
          <p> Individuals cryptocurrencies are digital and cannot be counterfeited or reversed arbitrarily by the sender, as with credit card charge-backs.When you give your credit card to a merchant, you give him or her access to your full credit line, even if the transaction is for a small amount. Credit cards operate on a “pull” basis, where the store initiates the payment and pulls the designated amount from your account. Cryptocurrency uses a “push” mechanism that allows the cryptocurrency holder to send exactly what he or she wants to the merchant or recipient with no further information.</p>
          <p><a class="btn btn-default" href="https://www.bestbitcoinexchange.io/" target="_blank" role="button">More Info on Exchange &raquo;</a></p>
        </div>
      </div>

      <hr>

      <footer>
        <p>&copy; MeLAB TradeMark</p>
      </footer>
    </div> <!-- /container -->

app/views/homes/currency.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h1 class="text-center">
                Best Rate From MeLAB
            </h1>
        </div>
        <div id="no-more-tables">
            <table class="col-md-12 table-bordered table-striped table-condensed cf">
        		<thead class="cf">
        			<tr>
        				<th>Code</th>
        				<th>Currency</th>
        				<th class="numeric">Price</th>
        				<th class="numeric">Code</th>
        				<th class="numeric">Exchange</th>
        			</tr>
        		</thead>
        		<tbody>
        			<tr>
        				<td data-title="Code">MYR</td>
        				<td data-title="Company">100 RINGGIT MALAYSIA</td>
        				<td data-title="Price" class="numeric">SGD</td>
        				<td data-title="Change" class="numeric">SINGAPORE DOLLAR</td>
        				<td data-title="Change %" class="numeric"><%= @rm_sg %></td>
        			</tr>
        			<tr>
        				<td data-title="Code">SGD</td>
        				<td data-title="Company">1 SINGAPORE DOLLAR</td>
        				<td data-title="Price" class="numeric">MYR</td>
        				<td data-title="Change" class="numeric">MALAYSIA RINGGIT</td>
        				<td data-title="Change %" class="numeric"><%= @sg_rm %></td>
        			</tr>
        			<tr>
        				<td data-title="Code">MYR</td>
        				<td data-title="Company">1 RINGGIT MALAYSIA</td>
        				<td data-title="Price" class="numeric">IDR</td>
        				<td data-title="Change" class="numeric">INDONESIA RUPPIAH</td>
        				<td data-title="Change %" class="numeric"><%= @rm_idr %></td>
        			</tr>
        			<tr>
        				<td data-title="Code">IDR</td>
        				<td data-title="Company">1000 INDONESIA RUPPIAH</td>
        				<td data-title="Price" class="numeric">MYR</td>
        				<td data-title="Change" class="numeric">MALAYSIA RINGGIT</td>
        				<td data-title="Change %" class="numeric"><%= @idr_rm %></td>
        			</tr>
        			<tr>
        				<td data-title="Code">MYR</td>
        				<td data-title="Company">100 RINGGIT MALAYSIA</td>
        				<td data-title="Price" class="numeric">TBH</td>
        				<td data-title="Change" class="numeric">THAI BAHT</td>
        				<td data-title="Change %" class="numeric"><%= @rm_baht %></td>
        			</tr>
        			<tr>
        				<td data-title="Code">TBH</td>
        				<td data-title="Company">1000 THAI BAHT</td>
        				<td data-title="Price" class="numeric">MYR</td>
        				<td data-title="Change" class="numeric">MALAYSIA RINGGIT</td>
        				<td data-title="Change %" class="numeric"><%= @baht_rm %></td>
        			</tr>
        		</tbody>
        	</table>
        </div>
    </div>
    <div class="row">
        <p class="bg-success" style="padding:10px;margin-top:20px"><small><a href="http://elvery.net/demo/responsive-tables/#no-more-tables" target="_blank">Link</a> to calculator</small></p>
    </div>
</div>

app/views/homes/index.html.erb
    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          <ul class="nav nav-sidebar"><% if user_signed_in? %> 
            <li class="active"><a href="#">Overview <span class="sr-only">(current)</span></a></li>
            <li><%= link_to 'Top Up e-Wallet', ewallets_path %></li>
            <li><a href="/currency">Exchange Rate</a></li>
            <li><a href="/crypto" data-toggle="tooltip" data-placement="right" title="Get the best rate now">CryptoCurrency Rate</a></li>
            <li><a href="/remit" data-toggle="tooltip" data-placement="right" title="Send money home as easy as 123">Bank Transfer</a></li>
            <li><a href="/transfer" data-placement="right" title="No one match us for fast and cheap">P2P Transfer</a></li>
            <li><a href="/value">Value Added Services</a></li>
          </ul>
          <ul class="nav nav-sidebar">
            <li> <%= link_to('Edit registration', edit_user_registration_path) %></li>
            <li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li><%end%>
           <li><%=  %></li>
            <% if current_user.superadmin_role? %>            
            <li><a href="">Bank Negara Dashboard</a></li>
            <li><a href="">Venture Capitalist Partner Dashboard</a></li>
          </ul>
			<p>Visible only for superadmins and supervisors! </p>
			<% end %>
        </div>
       
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
          <h1 class="page-header"> <%=current_user.email%> Dashboard</h1>
          <div class="row placeholders">
            <div class="col-xs-6 col-sm-3 placeholder">
              <%= link_to (image_tag"rm.jpg", class: "img-responsive",alt:"Generic placeholder thumbnail"), ringgit_path %>
              <h4>RinggitCoin</h4>
              <span class="text-muted"><%= number_to_currency(@ringgit) %></span>
            </div>
            <div class="col-xs-6 col-sm-3 placeholder">
               <%= link_to (image_tag"sgd.jpg", class: "img-responsive",alt:"Generic placeholder thumbnail"), sing_path %>
              <h4>SingCoin</h4>
              <span class="text-muted"><%= number_to_currency(@sing) %></span>
            </div>
            <div class="col-xs-6 col-sm-3 placeholder">
               <%= link_to (image_tag"bat.jpg", class: "img-responsive",alt:"Generic placeholder thumbnail"), baht_path%>
              <h4>BahtCoin</h4>
              <span class="text-muted"><%= number_to_currency(@baht) %></span>
            </div>
            <div class="col-xs-6 col-sm-3 placeholder">
              <%= link_to (image_tag"ripiah.jpg", class: "img-responsive",alt:"Generic placeholder thumbnail"), rupiah_path%>
              <h4>RupiahCoin</h4>
              <span class="text-muted"><%= number_to_currency(@rupiah) %></span>
            </div>
          </div>
          <h2 class="sub-header">Transaction Details</h2>
          <div class="table-responsive">
            <table class="table table-striped">
              <thead>
                <tr>
                  <th>Date</th>
                  <th>Description</th>
                  <th>Currency</th>
                  <th>Amount</th>
                 
                </tr>
              </thead>
              <tbody>
              <% @ewallet.each do |x| %>
                <tr>
                  <td><%= x.created_at %></td>
                  <td><%= x.description %> from <%= x.choice %></td>
                  <td><%= x.currency %></td>
                  <td><%= number_to_currency(x.balance) %></td>
                  <% end %>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
 

app/views/homes/new.html.erb
<h1> hello <%= current_user.email %>

app/views/homes/remit.html.erb
<br><br>
<div class="col-md-3"></div>
<div class="col-md-6">
  <div class="panel panel-primary">
    <div class="panel-heading">Welcome to MeLAB Bank Transfer</div>
    <div class="panel-body">
      <form accept-charset="UTF-8" action="http://simple-form-bootstrap.plataformatec.com.br/examples/create_basic" class="simple_form new_user_basic" enctype="multipart/form-data" id="new_user_basic" method="post" novalidate="novalidate"><div style="display:none"><input name="utf8" type="hidden" value="&#x2713;" /><input name="authenticity_token" type="hidden" value="YQbOHpiS3DwKbqLPAN5kBCvcSV2PS62lHn48DyI6cQY=" /></div>
  

  <div class="form-group email required user_basic_email"><label class="email required control-label" for="user_basic_email"><abbr title="required">*</abbr> Full Name of Recipient</label><input class="string email required form-control" id="user_basic_email" name="user_basic[email]" placeholder="Enter name" type="email" /><p class="help-block"></p></div>

  <div class="form-group password required user_basic_password"><label class="password required control-label" for="user_basic_password"><abbr title="required">*</abbr> Passport No/ Identification No</label><input class="password required form-control" id="user_basic_password" name="user_basic[password]" placeholder="Enter here" type="password" /><p class="help-block">We will keep this information private</p></div>

   <div class="form-group email required user_basic_email"><label class="email required control-label" for="user_basic_email"><abbr title="required">*</abbr> Recipient Bank Account No</label><input class="string email required form-control" id="user_basic_email" name="user_basic[email]" placeholder="Enter name" type="email" /><p class="help-block"></p></div>

  <div class="form-group boolean optional user_basic_active"><div class="checkbox"><input name="user_basic[active]" type="hidden" value="0" /><label class="boolean optional" for="user_basic_active"><input class="boolean optional" id="user_basic_active" name="user_basic[active]" type="checkbox" value="1" />Yes </label></div><p class="help-block">Recipient Residential Status</p></div>

  <div class="form-group check_boxes optional user_basic_choices"><label class="check_boxes optional control-label">Currency Choices</label><span class="checkbox"><label for="user_basic_choices_option_one_is_this_and_thatbe_sure_to_include_why_its_great"><input class="check_boxes optional" id="user_basic_choices_option_one_is_this_and_thatbe_sure_to_include_why_its_great" name="user_basic[choices][]" type="checkbox" value="Option one is this and that—be sure to include why it&#39;s great" />RinggitCoin</label></span><span class="checkbox"><label for="user_basic_choices_option_two_can_be_something_else_and_selecting_it_will_deselect_option_one"><input class="check_boxes optional" id="user_basic_choices_option_two_can_be_something_else_and_selecting_it_will_deselect_option_one" name="user_basic[choices][]" type="checkbox" value="Option two can be something else and selecting it will deselect option one" />SingCoin</label></span><input name="user_basic[choices][]" type="hidden" value="" />

  <span class="checkbox"><label for="user_basic_choices_option_one_is_this_and_thatbe_sure_to_include_why_its_great"><input class="check_boxes optional" id="user_basic_choices_option_one_is_this_and_thatbe_sure_to_include_why_its_great" name="user_basic[choices][]" type="checkbox" value="Option one is this and that—be sure to include why it&#39;s great" />BahtCoin</label></span><span class="checkbox"><label for="user_basic_choices_option_two_can_be_something_else_and_selecting_it_will_deselect_option_one"><input class="check_boxes optional" id="user_basic_choices_option_two_can_be_something_else_and_selecting_it_will_deselect_option_one" name="user_basic[choices][]" type="checkbox" value="Option two can be something else and selecting it will deselect option one" />RupiahCoin</label></span><input name="user_basic[choices][]" type="hidden" value="" /></div>

    <div class="form-group email required user_basic_email"><label class="email required control-label" for="user_basic_email"><abbr title="required">*</abbr> Amount</label><input class="string email required form-control" id="user_basic_email" name="user_basic[email]" placeholder="example :200.90" type="email" /><p class="help-block">The Fee is USD 0.30</p></div>

  <input class="btn btn-default" name="commit" type="submit" value="Transfer Now" />
</form>
    </div>
  </div>
</div>

</div>

app/views/homes/transfer.html.erb
  <br><br>
  <div class="container">

        <!-- Jumbotron Header -->
        <header class="jumbotron hero-spacer">
            <h1>MeLAB P2P Transfer</h1>
            <p>The best things in life are free. The second best only cost you usd 0.30!</p>
            <p><a class="btn btn-primary btn-large">Choose what best fit you!</a>
            </p>
        </header>

        <hr>

        <!-- Title -->
        <div class="row">
            <div class="col-lg-12">
                <h3>Latest Features</h3>
            </div>
        </div>
        <!-- /.row -->

        <!-- Page Features -->
        <div class="row text-center">

            <div class="col-md-3 col-sm-6 hero-feature">
                <div class="thumbnail">
                    <%= image_tag("p2p.jpg", class: "img-responsive",:size => "800x500") %>
                    <div class="caption">
                        <h3>P2P Transfer</h3>
                        <p>Instant, Secure and Free! This is our P2P transfer. Get your members to join MeLAB and transfer for free!</p>
                        <p>
                            
                            <!-- Button trigger modal -->
<button type="button" class="btn btn-primary btn-primary" data-toggle="modal" data-target="#myModal">
  Transfer Now!
</button>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">P2P Tansfer</h4>
      </div>
      <div class="modal-body">
            <div class="row">
  <div class="col-xs-6 col-sm-6">
  <p> Recipient name </p>
  <%= render "search" %>
  </div>

  <div class="col-xs-6 col-sm-6">
  <%= form_for (@ewallet) do |p| %>
  <p> Please choose your currency for transfer </p>
<select name="ewallet[currency]">
  <option value="ringgitcoin">RinggitCoin</option>
  <option value="singcoin">SingCoin</option>
  <option value="bahtcoin">BahtCoin</option>
  <option value="rupiahcoin">RupiahCoin</option>
</select><br><br>
  <%= p.label :balance %>:
  <%= p.number_field :balance %><br/>
  <h4><%= p.submit %></h4>
  <% end %></div>
</div>
      </div>
    </div>
  </div>
</div> <a href="#" class="btn btn-default">More Info</a>
                        </p>
                    </div>
                </div>
            </div>

            <div class="col-md-3 col-sm-6 hero-feature">
                <div class="thumbnail">
                    <%= image_tag("creditcard.jpg", class: "img-responsive",:size => "800x500") %>
                    <div class="caption">
                        <h3>Debit Card</h3>
                        <p>We provide you local debit card even when you travelling oversea. Not multicurrency card that charge exorbitant fee. That truly a mobile banking, anytime anyway</p>
                        <p>
                            <a href="#" class="btn btn-primary">Apply Now!</a> <a href="#" class="btn btn-default">More Info</a>
                        </p>
                    </div>
                </div>
            </div>

            <div class="col-md-3 col-sm-6 hero-feature">
                <div class="thumbnail">
                   <%= image_tag("rm.jpg", class: "img-responsive",:size => "800x500") %>
                    <div class="caption">
                        <h3>Cash Facilities</h3>
                        <p>No worry too! Our local Debit card can be used as ATM. We mean local ATM even when you travel oversea!</p>
                        <p>
                            <a href="#" class="btn btn-primary">Buy Now!</a> <a href="#" class="btn btn-default">More Info</a>
                        </p>
                    </div>
                </div>
            </div>

            <div class="col-md-3 col-sm-6 hero-feature">
                <div class="thumbnail">
                    <%= image_tag("sending_money.png", class: "img-responsive",:size => "800x500") %>
                    <div class="caption">
                        <h3>Receive & Send</h3>
                        <p>Need urgent fund when travelling ? Ask help and received instantly from families or friends. Anyway Anytime. </p>
                        <p>
                            <a href="#" class="btn btn-primary">Buy Now!</a> <a href="#" class="btn btn-default">More Info</a>
                        </p>
                    </div>
                </div>
            </div>

        </div>
        <!-- /.row -->

        <hr>

        <!-- Footer -->
        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; MeLAB Design</p>
                </div>
            </div>
        </footer>

app/views/homes/value.html.erb
     <div class="jumbotron">
        <center><h1>Convenient at your fingertips!</h1>
        <p class="lead">Top up your eWallet now and enjoy greater saving and convenient!</p>
        <p><a class="btn btn-lg btn-success" href="#" role="button">Top up today</a></p></center>
      </div>
<div class="row">
  <div class="col-sm-4"><h1> Top Up Telco </h1>
<br><br>
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal" data-whatever="@mdo">Digi Prepaid</button>
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal" data-whatever="@fat">Celcom Xpad Prepaid</button>
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal" data-whatever="@getbootstrap">Maxis Prepaid</button><br><br><br>
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal" data-whatever="@mdo">Tune Talk Prepaid</button>
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal" data-whatever="@fat">One XOX Prepaid</button>
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal" data-whatever="@getbootstrap">U Mobile Prepaid</button></div>

  <div class="col-sm-4"><h1>Utility Payment</h1><br><br>
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal" data-whatever="@mdo">Unifi</button>
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal" data-whatever="@fat">Tenaga Nasional Berhad</button>
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal" data-whatever="@getbootstrap">Syabas</button><br><br><br>
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal" data-whatever="@mdo">Indah Water</button>
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal" data-whatever="@fat">Astro</button>
</div>

  <div class="col-sm-4"><h1>Booking Services</h1>
<br><br>
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal" data-whatever="@mdo">Air Asia </button>
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal" data-whatever="@fat">Fire Fly</button>
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal" data-whatever="@getbootstrap">MAS Airline</button><br><br><br>
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal" data-whatever="@mdo">Malindo Air</button>
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal" data-whatever="@fat">KTM Services</button>
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal" data-whatever="@getbootstrap">Malaysia Long Haul Bus</button>
  </div>
</div>
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="exampleModalLabel">Payment</h4>
      </div>
      <div class="modal-body">
        <form>
          <div class="form-group">
            <label for="recipient-name" class="control-label">Recipient Info:</label>
            <input type="text" class="form-control" id="recipient-name">
          </div>
          <div class="form-group">
            <label for="message-text" class="control-label">Amount:</label>
            <textarea class="form-control" id="message-text"></textarea>
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Proceed</button>
      </div>
    </div>
  </div>
</div>