config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
    devise_for :users, controllers: {
      sessions: 'users/sessions',
      passwords: 'users/passwords',
      registrations: 'users/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "homes#index"
  resources :homes
  resources :accounts
  resources :ewallets

  get '/home' => "homes#index"
  get '/ringgit' => "ewallets#ringgit"
  get '/rupiah' => "ewallets#rupiah"
  get '/sing' => "ewallets#sing"
  get '/baht' => "ewallets#baht"
  get '/remit' => "homes#remit"
  get '/transfer' => "homes#transfer"
  get '/value' => "homes#value"
  get '/crypto' => "homes#crypto"
  get '/currency' => "homes#currency"

end

app/models/ewallet.rb
class Ewallet < ApplicationRecord
  belongs_to :user
end

app/controllers/ewallets_controller.rb
class EwalletsController < ApplicationController
	before_action :find, only: [:edit, :update, :destroy]

	def index
		@ewallets = Ewallet.all.order(created_at: :desc)
	end

	def show
		@ewallet = Ewallet.where(user_id: current_user.id)
		@ringgit = @ewallet.where(currency:"ringgitcoin")
		@sing = @ewallet.where(currency:"singcoin")
		@rupiah = @ewallet.where(currency:"rupiahcoin")
		@baht = @ewallet.where(currency:"bahtcoin")
	end

	def ringgit
		@ewallet = Ewallet.where(user_id: current_user.id)
		@ringgit = @ewallet.where(currency:"ringgitcoin")
		render 'ewallets/ringgit'
	end

	def rupiah
		@ewallet = Ewallet.where(user_id: current_user.id)
		@rupiah = @ewallet.where(currency:"rupiahcoin")
		render 'ewallets/rupiah'
	end

	def sing
		@ewallet = Ewallet.where(user_id: current_user.id)
		@sing = @ewallet.where(currency:"singcoin")
		render 'ewallets/sing'
	end

	def baht
		@ewallet = Ewallet.where(user_id: current_user.id)
		@baht = @ewallet.where(currency:"bahtcoin")
		render 'ewallets/baht'
	end

	def new
		@ewallet = current_user.ewallets.build
	end

	def create
		@ewallet = current_user.ewallets.build(ewallet_params)
		if @ewallet.save
		flash[:sucess] = 'You succesfully top up!'
		redirect_to root_path
	else
		render 'new'
	end
	end

	def edit
	end

	def update
		@ewallet.update(ewallet_params)
	end

	def destroy
		@ewallet.destroy
		redirect_to root_path
	end

	private

	def find
		@ewallet = Ewallet.find(params[:id])
	end

	def ewallet_params
		params.require(:ewallet).permit(:currency, :description, :choice, :balance)
	end

end

app/helpers/ewallets_helper.rb
module EwalletsHelper
end

app/views/ewallets/_form.html.erb
<div class="container top-margin">
    <div class="row">
      <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
        <div class="greeting">Hi, <%=current_user.email%>! Let’s start your ewallet
          <br> and start saving!
        </div>
        <br>
        <br>
        <div class="small">STEP 1</div>
        <div class="place">What kind of currency you want to top up ???</div>

<%= form_for (@ewallet) do |p| %>
<select name="ewallet[currency]">
  <option value="ringgitcoin">RinggitCoin</option>
  <option value="singcoin">SingCoin</option>
  <option value="bahtcoin">BahtCoin</option>
  <option value="rupiahcoin">RupiahCoin</option>
</select><br><br>

        <div class="small">STEP 2</div>
        <div class="place">Please choose the top up method</div>
  <select name="ewallet[choice]">
  <option value="cash deposit machine">Cash Deposit Machine</option>
  <option value="online transfer">Online Transfer</option>
  <option value="crypto transfer">Crypto Transfer</option>
  <option value="paypal">PayPal</option>
</select><br><br>


        <div class="small">STEP 3</div>
        <div class="place">Please enter the amount</div>
  <select name="ewallet[description]">
  <option value="credit">Transfer Immediately</option>
  </select>
  <%= p.label :balance %>:
  <%= p.number_field :balance %><br/>
  <h4><%= p.submit %></h4>
<%end%>

app/views/ewallets/baht.html.erb
<center><h2 class="sub-header">Transaction Details</h2></center>
          <div class="table-responsive">
            <table class="table table-striped">
            <center><h3>BahtCoin</h3></center>
              <thead>
                <tr>
                  <th>Date</th>
                  <th>Description</th>
                  <th>Currency</th>
                  <th>Amount</th>
                  <th>Balance</th>
                </tr>
              </thead>
              <tbody>
              <% running_total = 0 %>
              <% @baht.each do |x| %>
                <tr>
                  <td><%= x.created_at %></td>
                  <td><%= x.description %> from <%= x.choice %></td>
                  <td><%= x.currency %></td>
                  <td><%= number_to_currency(x.balance) %></td>
                  <% running_total = running_total + (x.balance) %>
                  <% end %>
                  <td><%= number_to_currency(running_total) %></td>
                </tr>
              </tbody>
            </table>
          </div>

app/views/ewallets/index.html.erb
<div class="container-fluid bg-3 text-center">    
  <h1 class="margin">Online Banking</h1><br>
  <div class="row">
    <div class="col-sm-4">
      <%= link_to image_tag("cimb.png", :height =>"200", :width => "225"), new_ewallet_path%>
       <p>Cimb Click</p>
    </div>
    <div class="col-sm-4"> 
      <%= link_to image_tag("m2u", :height =>"200", :width => "225"), new_ewallet_path%>
    <p>Maybank2U</p>
    </div>
      <%= link_to image_tag("rhb.png", :height =>"200", :width => "225"), new_ewallet_path%> 
      <p>RHB Now</p>
    </div>
  </div>
</div>
<br><br><br>
<div class="container-fluid bg-3 text-center">    
  <h1 class="margin">Cash & Others</h1><br>
  <div class="row">
    <div class="col-sm-4">
      <%= link_to image_tag("cdm.jpg", :height =>"200", :width => "225"), new_ewallet_path%>
         <p>Cash Deposit Machine</p>
    </div>
    <div class="col-sm-4"> 
       <%= link_to image_tag("paypal.png", :height =>"200", :width => "225"), new_ewallet_path%>
         <p>PayPal</p>
    </div>
    <div class="col-sm-4"> 
      <%= link_to image_tag("bitcoin.jpg", :height =>"200", :width => "225"), new_ewallet_path%>
         <p>CryptoCurrencies Exchange</p>
    </div>
  </div>
</div>

app/views/ewallets/new.html.erb
<br><br><br><br>

<%= render 'form' %>

app/views/ewallets/ringgit.html.erb
<center><h2 class="sub-header">Transaction Details</h2></center>
          <div class="table-responsive">
            <table class="table table-striped">
            <center><h3>RinggitCoin</h3></center>
              <thead>
                <tr>
                  <th>Date</th>
                  <th>Description</th>
                  <th>Currency</th>
                  <th>Amount</th>
                  <th>Balance</th>
                </tr>
              </thead>
              <tbody>
              <% running_total = 0 %>
              <% @ringgit.each do |x| %>
                <tr>
                  <td><%= x.created_at %></td>
                  <td><%= x.description %> from <%= x.choice %></td>
                  <td><%= x.currency %></td>
                  <td><%= number_to_currency(x.balance) %></td>
                  <% running_total = running_total + (x.balance) %>
                  <% end %>
                  <td><%= number_to_currency(running_total) %></td>
                </tr>
              </tbody>
            </table>
          </div>

app/views/ewallets/rupiah.html.erb
<center><h2 class="sub-header">Transaction Details</h2></center>
          <div class="table-responsive">
            <table class="table table-striped">
            <center><h3>RupiahCoin</h3></center>
              <thead>
                <tr>
                  <th>Date</th>
                  <th>Description</th>
                  <th>Currency</th>
                  <th>Amount</th>
                  <th>Balance</th>
                </tr>
              </thead>
              <tbody>
              <% running_total = 0 %>
              <% @rupiah.each do |x| %>
                <tr>
                  <td><%= x.created_at %></td>
                  <td><%= x.description %> from <%= x.choice %></td>
                  <td><%= x.currency %></td>
                  <td><%= number_to_currency(x.balance) %></td>
                  <% running_total = running_total + (x.balance) %>
                  <% end %>
                  <td><%= number_to_currency(running_total) %></td>
                </tr>
              </tbody>
            </table>
          </div>

app/views/ewallets/show.html.erb
<h1> @ewallet.currency</h1>
<p> @ewallet.balance</p>
<p> @ewallet.description</p>
<p> @ewallet.choice</p>

app/views/ewallets/sing.html.erb
<center><h2 class="sub-header">Transaction Details</h2></center>
          <div class="table-responsive">
            <table class="table table-striped">
            <center><h3>SingCoin</h3></center>
              <thead>
                <tr>
                  <th>Date</th>
                  <th>Description</th>
                  <th>Currency</th>
                  <th>Amount</th>
                  <th>Balance</th>
                </tr>
              </thead>
              <tbody>
              <% running_total = 0 %>
              <% @sing.each do |x| %>
                <tr>
                  <td><%= x.created_at %></td>
                  <td><%= x.description %> from <%= x.choice %></td>
                  <td><%= x.currency %></td>
                  <td><%= number_to_currency(x.balance) %></td>
                  <% running_total = running_total + (x.balance) %>
                  <% end %>
                  <td><%= number_to_currency(running_total) %></td>
                </tr>
              </tbody>
            </table>
          </div>