config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
    devise_for :users, controllers: {
      sessions: 'users/sessions',
      passwords: 'users/passwords',
      registrations: 'users/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "homes#index"
  resources :homes
  resources :accounts
  resources :ewallets

  get '/home' => "homes#index"
  get '/ringgit' => "ewallets#ringgit"
  get '/rupiah' => "ewallets#rupiah"
  get '/sing' => "ewallets#sing"
  get '/baht' => "ewallets#baht"
  get '/remit' => "homes#remit"
  get '/transfer' => "homes#transfer"
  get '/value' => "homes#value"
  get '/crypto' => "homes#crypto"
  get '/currency' => "homes#currency"

end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :user
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
	before_action :find, only: [:show, :edit, :destroy, :update]

	def index
		@accounts = Account.all.order(created_at: :desc)
	end

	def show
	end

	def new
		@account = Account.new
	end

	def create
		@account = Account.new(account_params)
		if @account.save
			flash[:success] = "You successfully top up your e-Wallet!"
			redirect_to root_path
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		@account.update(account_params)
	end

	def destroy
		@account.destroy
		redirect_to root_path

	end

	private

	def find
		@account= Account.find(params[:id])
	end

	def account_params
		params.require(:account).permit(:ringgitcoin, :bahtcoin, :singcoin, :rupiahcoin)
	end

end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_form.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-4 col-md-4">
    </div>
    <div class="col-sm-4 col-md-4">
  <%= simple_form_for @account do |f| %>
  <%= f.input :ringgitcoin %>
  <%= f.input :bahtcoin %>
  <%= f.input :singcoin %>
  <%= f.input :rupiahcoin %>
  <%= f.button :submit %>
  <% end %>
    </div>
    </div>
  </div>

app/views/accounts/index.html.erb
<div class="container-fluid bg-3 text-center">    
  <h1 class="margin">Online Banking</h1><br>
  <div class="row">
    <div class="col-sm-4">
      <%= link_to image_tag("cimb.png", :height =>"200", :width => "225"), new_account_path%>
       <p>Cimb Click</p>
    </div>
    <div class="col-sm-4"> 
      <%= link_to image_tag("m2u", :height =>"200", :width => "225"), new_account_path%>
    <p>Maybank2U</p>
    </div>
      <%= link_to image_tag("rhb.png", :height =>"200", :width => "225"), new_account_path%> 
      <p>RHB Now</p>
    </div>
  </div>
</div>
<br><br><br>
<div class="container-fluid bg-3 text-center">    
  <h1 class="margin">Cash & Others</h1><br>
  <div class="row">
    <div class="col-sm-4">
      <%= link_to image_tag("cdm.jpg", :height =>"200", :width => "225"), new_account_path%>
         <p>Cash Deposit Machine</p>
    </div>
    <div class="col-sm-4"> 
       <%= link_to image_tag("paypal.png", :height =>"200", :width => "225"), new_account_path%>
         <p>PayPal</p>
    </div>
    <div class="col-sm-4"> 
      <%= link_to image_tag("bitcoin.jpg", :height =>"200", :width => "225"), new_account_path%>
         <p>CryptoCurrencies Exchange</p>
    </div>
  </div>
</div>

app/views/accounts/new.html.erb
<br><br><br><br>
<center><h1> Enter your amount to top up </h1></center>
<%= render 'form' %>